# Generated by Django 3.1.5 on 2021-01-24 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('advert_slug', models.SlugField(unique=True, verbose_name='ЧПУ')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес дома')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('area', models.IntegerField(verbose_name='Общая площадь')),
                ('year', models.IntegerField(verbose_name='Год постройки')),
                ('house_type', models.CharField(choices=[('house', 'дом'), ('cottage', 'коттедж')], default=None, max_length=10, verbose_name='тип дома')),
                ('garage', models.IntegerField(default=0, verbose_name='Гараж')),
                ('advert_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
                ('advert_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('realtor', 'риелтор'), ('company', 'агентство'), ('developer', 'застройщик'), ('owner', 'собственник')], default=None, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('advert_slug', models.SlugField(unique=True, verbose_name='ЧПУ')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес дома')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('area', models.IntegerField(verbose_name='Общая площадь')),
                ('year', models.IntegerField(verbose_name='Год постройки')),
                ('floors', models.IntegerField(default=1, verbose_name='Этажность дома')),
                ('apartment_floor', models.IntegerField(default=1, verbose_name='Номер этажа')),
                ('advert_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
                ('advert_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления')),
            ],
            options={
                'verbose_name': 'Квартиру',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
