# Generated by Django 3.1.7 on 2021-03-04 09:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='ЧПУ')),
                ('advert_category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Категории')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес дома')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('area', models.IntegerField(verbose_name='Общая площадь')),
                ('year', models.IntegerField(verbose_name='Год постройки')),
                ('building_type', models.CharField(choices=[('0', '----'), ('brick', 'кирпичный'), ('monolithic', 'монолитный'), ('wooden', 'деревянный'), ('aerated_concrete', 'газобетонный блок'), ('foam_concrete', 'пенобетонный блок')], default=None, max_length=30, verbose_name='Тип дома')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True, null=True)),
                ('advert_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.advert')),
                ('floors', models.PositiveIntegerField(default=1, verbose_name='Этажность дома')),
                ('apartment_floor', models.PositiveIntegerField(default=1, verbose_name='Номер этажа')),
            ],
            options={
                'verbose_name': 'Квартиру',
                'verbose_name_plural': 'Квартиры',
            },
            bases=('main.advert',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.advert')),
                ('garage', models.BooleanField(default=False, verbose_name='Гараж')),
                ('plot', models.FloatField(default=0.0, verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
            bases=('main.advert',),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(blank=True, choices=[('realtor', 'риелтор'), ('company', 'агентство'), ('developer', 'застройщик'), ('owner', 'собственник')], max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профили',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
