# Generated by Django 3.1.5 on 2021-01-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_floor',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер этажа'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floors',
            field=models.PositiveIntegerField(default=1, verbose_name='Этажность дома'),
        ),
    ]
