# Generated by Django 3.1.5 on 2021-01-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='plot',
            field=models.PositiveIntegerField(default=0, verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='house',
            name='garage',
            field=models.BooleanField(default=False, verbose_name='Гараж'),
        ),
    ]
