# Generated by Django 3.1.7 on 2021-03-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(default=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
        ),
    ]
