# Generated by Django 3.1.5 on 2021-01-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210124_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_type',
        ),

        migrations.AddField(
            model_name='apartment',
            name='building_type',
            field=models.CharField(
                choices=[
                    ('0', '----'),
                    ('brick', 'кирпичный'), ('monolithic', 'монолитный'),
                    ('wooden', 'деревянный'), ('aerated_concrete', 'газобетонный блок'),
                    ('foam_concrete', 'пенобетонный блок')],
                default=0,
                max_length=30,
                verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='house',
            name='building_type',
            field=models.CharField(
                choices=[
                    ('0', '----'),
                    ('brick', 'кирпичный'), ('monolithic', 'монолитный'),
                    ('wooden', 'деревянный'), ('aerated_concrete', 'газобетонный блок'),
                    ('foam_concrete', 'пенобетонный блок')],
                default=0,
                max_length=30,
                verbose_name='Тип дома'),
        ),

    ]
