# Generated by Django 3.1.5 on 2021-01-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210128_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='advert_slug',
            new_name='slug',
        ),
    ]
