# Generated by Django 3.1.5 on 2021-01-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', 'cahnge_house_plot'),
        ('main', '0003_auto_20210124_2222'),
    ]

    operations = [
    ]
