# Generated by Django 3.1.5 on 2021-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210128_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('realtor', 'риелтор'), ('company', 'агентство'), ('developer', 'застройщик'), ('owner', 'собственник')], max_length=20, null=True),
        ),
    ]
