# Generated by Django 3.1.7 on 2021-03-05 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210304_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('title', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('description', models.TextField(verbose_name='Описание объекта')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'user_advert',
                'managed': False,
            },
        ),
    ]
