# Generated by Django 3.1.5 on 2021-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210124_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building_type',
            field=models.CharField(choices=[('0', '----'), ('brick', 'кирпичный'), ('monolithic', 'монолитный'), ('wooden', 'деревянный'), ('aerated_concrete', 'газобетонный блок'), ('foam_concrete', 'пенобетонный блок')], default=None, max_length=30, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_type',
            field=models.CharField(choices=[('0', '----'), ('brick', 'кирпичный'), ('monolithic', 'монолитный'), ('wooden', 'деревянный'), ('aerated_concrete', 'газобетонный блок'), ('foam_concrete', 'пенобетонный блок')], default=None, max_length=30, verbose_name='Тип дома'),
        ),
    ]
