# Generated by Django 3.1.6 on 2021-02-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210204_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={
                'verbose_name': 'Профили',
                'verbose_name_plural': 'Профиль'},
        ),
    ]
