# Generated by Django 3.1.6 on 2021-02-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
