# Generated by Django 3.1.6 on 2021-02-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_advert_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
