# Generated by Django 3.1.7 on 2021-02-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_advert_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['-id'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
