# Generated by Django 3.1.5 on 2021-01-24 21:03

from django.db import migrations, models

#

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210124_2103'),
    ]

    operations = [

        migrations.AlterField(
            model_name='house',
            name='plot',
            field=models.FloatField(default=0.00, verbose_name='Участок'),
        ),

    ]

