# Generated by Django 3.1.5 on 2021-01-24 21:03

from django.db import migrations, models

def set_house_plot(apps, schema_editor):
    House = apps.get_model('main', 'House')
    db_alias = schema_editor.connection.alias

    for house in House.objects.using(db_alias).all():
        if house.garage:
            house.plot = 10.0
        house.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210124_2303'),
    ]

    operations = {

        migrations.AlterField(
            model_name='house',
            name='plot',
            field=models.FloatField(default=0.00, verbose_name='Участок'),
        ),

        migrations.RunPython(set_house_plot),
    }

